image: alpine:latest
stages:
  - deploy
Deploy Development:
  environment: Development
  stage: deploy
  script:
    - which ssh-agent || ( apk update && apk add openssh-client wget curl git php php-curl php-openssl php-json php-phar php-dom php-zip php-iconv php-mbstring unzip && rm /var/cache/apk/*)
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ( echo "$SSH_PRIVATE_KEY" | tr -d '\r') >> ~/.ssh/id_rsa
    - echo "$CI_COMMIT_REF_NAME"
    - ( echo "$SSH_CONFIG_SERVER") >> ~/.ssh/config
    - chmod 400 ~/.ssh/id_rsa
    - ssh root@server "cd $SERVER_PATH && git fetch && git checkout $CI_COMMIT_REF_NAME && git pull origin $CI_COMMIT_REF_NAME"
    - rm -rf ~/.ssh/id_rsa